### ISSUE TITLE
Linker warning

### ISSUE THREAD

**Issue by parski** [KatalysatorAB/BeaconSDK-iOS#2]
Hello!

We have been getting a warning when compiling with your SDK. We use the latest version (1.9.4) via CocoaPods. Deployment target is iOS 9.

```
ld: Auto-Linking supplied ‘/Users/travis/build/~/~/Pods/KatalysatorSDK/KatalysatorSDK.framework/KatalysatorSDK’, framework linker option at /Users/travis/build/~/~/Pods/KatalysatorSDK/KatalysatorSDK.framework/KatalysatorSDK is not a dylib
```

Please fix this.

**Comment by svenroed** [comment]
I tried to reproduce this with a simple project (ObjC & Swift) from scratch but so far without luck. Can you share additional details from the Podfile or if you set additional build/linker warning flags?

**Comment by parski** [comment]
My friend put this together.

https://github.com/spekke/GlimrSDK-iOS-Example-Warning

It demonstrates the issue if you run the tests.

@svenroed

**Comment by svenroed** [comment]
Thanks a lot, we will look into this.

**Comment by svenroed** [comment]
Thanks for the project @parski, now I was able to reproduce the case running your tests. 
It seems like add "-framework "KatalysatorSDK" to the "OTHER_LDFLAGS" key in the Build Settings for "katalysatorwarningTests" does the trick. 

Hope this helps, 
Best,
Sven

**Comment by svenroed** [comment]
Feel free to reopen if the suggested change doesn't fix it.
